
let quotes=[

    'I don\'t know what I want, so don\'t ask me /\'Cause I\'m still trying to figure it out',
    'So watch me strike a match on all my wasted time.',
    'I\'ll be strong, I\'ll be wrong, oh but life goes on…',
    ' And when you take, you take the very best of me.',
    'But no one notices until it\'s too late to do anything.',
    'Our song is the slamming screen door, sneakin\' out late, tapping on your window.',
    ' And I don\'t know why, but with you I\'d dance in a storm in my best dress, fearless.',
    'But in your life, you\'ll do things greater than dating the boy on the football team…But I didn\'t know it at fifteen.',
    'I\'ve found time can heal most anything and you just might find who you\'re supposed to be.',
    'Romeo, save me. They\'re trying to tell me how to feel. This love is difficult but it\'s real.',
    'Why are people always leaving? I think you and I should stay the same.',
    'My mistake, I didn\'t know to be in love you had to fight to have the upper hand.',    'this is a big world, that was a small town there in my rear view mirror disappearing now',
    'You\'ve got a smile that could light up this whole town.',
    ' And we know it\'s never simple, never easy. Never a clean break, no one here to save me.',
    'You took a swing, I took it hard. And down here from the ground I see who you are.',
    ' All this time I was wasting, hoping you would come around… I\'ve been giving out chances every time and all you do is let me down.',
    ' And then you feel so low you can\'t feel nothing at all.',
    'It rains when you\'re here and it rains when you\'re gone.',
    'these walls that they put up to hold us back will fall down…',
    'My mind forgets to remind me you\'re a bad idea.',
    'It turns out freedom ain\'t nothing but missing you.',
    ' She floats down the aisle like a pageant queen, but I know you wish it was me… don’t you?',
    'I lived in your chess game, but you changed the rules every day.',
    'I’m shining like fireworks over your sad, empty town.',
    ' Someday I\'ll be living in a big, old city and all you\'re ever gonna be is mean.',
    'I\'d tell you I miss you, but I don\'t know how, I\'ve never heard silence quite this loud.',
    'this is looking like a contest of who can act like they care less. But I liked it better when you were on my side.',
    ' And don\'t lose the way that you dance around in your pj\'s getting ready for school.',
    'this night is sparkling, don\'t you let it go. I\'m wonderstruck, blushing all the way home.',
    '2AM, who do you love?',
    'Your string of lights is still bright to me… Who you are is not where you\'ve been.',
    'today is never too late to be brand new.',
    'You and I walk a fragile line; I have known it all this time. But I never thought I\'d live to see it break.',
    'I don\'t know how to be something you miss.',
    'Bring on all the pretenders. One day, we will be remembered.',
    'We are alone with our changing minds. We fall in love \'til it hurts or bleeds or fades in time.',
    'Love is a ruthless game unless you play it good and right.',
    'He\'s long gone when he\'s next to me and I realize the blame is on me.',
    'No apologies. He\'ll never see you cry. Pretends he doesn\'t know that he\'s the reason why.',
    'the saddest fear comes creeping in - that you never loved me or her, or anyone, or anything...',
    '…That magic\'s not here no more. And I might be OK, but I\'m not fine at all.',
    ' And your mother\'s telling stories about you on a tee ball team. You taught me \'bout your past, thinking your future was me.',
    'I forget about you long enough to forget why I needed to...',
    'Maybe we got lost in translation, maybe I asked for too much. But maybe this thing was a masterpiece \'til you tore it all up. Running scared, I was there, I remember it all too well.',
    'You call me up again just to break me like a promise, so casually cruel in the name of being honest.',
    'time won\'t fly, it\'s like I\'m paralyzed by it. I\'d like to be my old self again, but I\'m still trying to find it.',
    'cause there we are again, when I loved you so. Back before you lost the one, real thing you\'ve ever known.',
    'Now you mail back my things and I walk home alone / But you keep my old scarf from that very first week, \'cause it reminds you of innocence and it smells like me.',
    'We\'re happy, free, confused, and lonely at the same time. It\'s miserable and magical.',
    'I wish I could run to you. And I hope you know that every time I don\'t I almost do.',
    'You wear your best apology, but I was there to watch you leave.',
    'But sometimes I wonder how you think about it now.',
    'But I don’t wanna dance if I’m not dancing with you.',
    'Words, how little they mean when you\'re a little too late.',
    '“And they tell you that you’re lucky, but you’re so confused, \'cause you don’t feel pretty, you just feel used.',
    'I\'ve been spending the last eight months thinking all love ever does is break and burn and end…',
    'And what do you do when the one who means the most to you is the one who didn\'t show?',
    'Your close friends always seem to know / When there\'s something really wrong',
    'You called me later / And said, \'I\'m sorry I didn\'t make it\' / And I said, \'I\'m sorry, too\'',
    'Loving him is like driving a new Maserati down a dead-end street / Faster than the wind, passionate as sin, ending so suddenly',
    'the lights are so bright, but they never blind me.',
    'Love\'s a game, wanna play?',
    'But you\'ll come back each time you leave \'cause darling, I\'m a nightmare dressed like a daydream.',
    'When we go crashing down, we come back every time \'cause we never go out of style.',
    'I got that red lip, classic thing that you like.',
    'the rest of the world was black and white, but we were in screaming color.',
    'the more I think about it now, the less I know, all I know is that you drove us off the road.',
    'People like you always want back the love they pushed aside, but people like me are gone forever when you say goodbye.',
    'Why\'d you have to go and lock me out when I let you in?',
    'While you\'ve been getting down and out about the liars and the dirty, dirty cheats of the world… You could\'ve been getting down to this sick beat.',
    'We\'re a crooked love in a straight line down.',
    ' And I wish you knew that I miss you too much to be mad anymore.',
    'You give me everything and nothing.',
    'Makes you wanna run and hide, but it made us turn right back around.',
    'Band-aids don\'t fix bullet holes. You say sorry just for show.',
    ' Someday when you leave me, I bet these memories follow you around.',
    'When you\'re young, you just run, but you come back to what you need.',
    'this love left a permanent mark.',
    'Your kiss, my cheek / I watch you leave / Your smile, my ghost / I fall to my knees',
    'It was months and months of back and forth, you\'re still all over me like a wine-stained dress I can\'t wear anymore.',
    'When I was drowning that\'s when I could finally breathe.',
    'Just because you\'re clean, don\'t mean you don\'t miss it.',
    'didn\'t it all seem new and exciting? …It\'s all fun and games \'til somebody loses their mind.',
    'You search the world for something else to make you feel like what we had. And in the end in wonderland, we both went mad.',
    'Heartbreak is the national anthem, we sing it proudly.',
    'they\'ll take their shots, but we are bulletproof.',
    ' So I punched a hole in the roof / Let the flood carry away all my pictures of you.',
    'When all you wanted / Was to be wanted / Wish you could go back / And tell yourself what you know now',
    '32 and still growing up now / Who you are is not what you did / You’re still an innocent',
    'We play dumb / But we know exactly what we\'re doing',
    'Please don\'t ever become a stranger whose laugh I could recognize anywhere',
    'Can we always be this close forever and ever?',
    'I\'m only seventeen / I don\'t know anything but I know I miss you',
    'I was walking home on broken cobblestones just thinking of you, when she pulled up like a figment of my worst intentions',
    'You play stupid games, you win stupid prizes',
    'I had a marvelous time ruining everything',
    'Untouchable, burning brighter than the sun / And when you’re close I feel like coming undone',
    'Barefoot in the kitchen / Sacred new beginnings / That became my religion, listen',
    'I could build a castle out of all the bricks they threw at me',
    'Cold was the steel of my axe to grind for the boys who broke my heart / Now I send their babies presents',
    'He says he\'s so in love / He\'s finally got it right / I wonder if he knows he\'s all I think about at night',
    'Back when you fit in my poems like a perfect rhyme',
    'I once believed love would be burning red / But it\'s golden',
    'I think I\'ve seen this film before / And I didn\'t like the ending / You\'re not my homeland anymore / So what am I defending now?',
    'He said the way my blue eyes shined / Put those Georgia stars to shame that night / I said, \'that\'s a lie',
    'the monsters turned out to be just trees / When the sun came up you were looking at me',
    'the night you danced like you knew our lives would never be the same / You held your head like a hero / On a history book page / It was the end of a decade / But the start of an age',
    'I can\'t decide if it\'s a choice: Getting swept away',
    'they told me all of my cages were mental / So I got wasted like all my potential',
    'But she wears short skirts / I wear T-shirts / She\'s cheer captain / And I\'m on the bleachers',
    'I don\'t like that falling feels like flying till the bone crush.',
    'I\'m doing good, I\'m on some new shit / Been saying \'yes\' instead of \'no\' / I thought I saw you at the bus stop, I didn\'t though',
    'I guess you never know, never know / And if you wanted me, you really should\'ve showed',
    'I persist and resist the temptation to ask you / If one thing had been different / Would everything be different today?',
    'When you are young they assume you know nothing',
    'You drew stars around my scars / But now I\'m bleedin',
    'I knew you\'d miss me once the thrill expired / And you\'d be standin\' in my front porch light / And I knew you\'d come back to me',
    'You wear the same jewels that I gave you, as you bury me',
    'We gather stones, never knowing what they\'ll mean / Some to throw, some to make a diamond ring',
    'You know I didn\'t want to have to haunt you / But what a ghostly scene',
    'do you remember when I pulled up and said \'get in the car\' / And then cancelled my plans just in case you called',
    'to live for the hope of it all / Cancel plans just in case you\'d call / And say, \'Meet me behind the mall\'',
    'Bold was the waitress on our three-year trip / Getting lunch down by the Lakes / She said I looked like an American singer',
    'time, mystical time / Cutting me open, then healing me fine / Were there clues I didn\'t see?',
    'One single thread of gold tied me to you',
    'I know where it all where wrong, your favorite song was playing from the far side of the gym / I was nowhere to be found I hate the crowds / Plus I saw you dance with him',
    'Knew I was a robber first time that he saw me / Stealing hearts and running off and never sayin\' sorry',
    'I swear I don\'t love the drama, it loves me',
    'I bury hatchets, but I keep maps of where I put \'em',
    'Love made me crazy, if it doesn\'t, you ain\'t doin\' it right',
    'My name is whatever you decide / And I\'m just gonna call you mine',
    'Handsome, you\'re a mansion with a view',
    'Sometimes I wonder when you sleep / Are you ever dreaming of me?',
    'the world goes on another day, another drama / But not for me, all I think about is karma.',
    'I\'ve got a list of names and yours is in red, underlined / I check it once, then I check it twice',
    'You asked me for a place to sleep, locked me out and threw a feast',
    'You know I\'m not a bad girl, but I / Do bad things with you',
    'You did a number on me but, honestly, baby, who\'s counting?',
    'Ocean blue eyes looking in mine / I feel like I might sink and drown and die',
    'You make me so happy it turns back to sad / There\'s nothing I hate more than what I can\'t have / And you are so gorgeous it makes me so mad',
    'We were jet-set, Bonnie and Clyde / Until I switched to the other side / It\'s no surprise I turned you in / \'cause us traitors never win',
    'We met a few weeks ago / Now you try on callin\' me \'Baby\' like tryin\' on clothes',
    'Your love is a secret I\'m hoping, dreaming, dying to keep',
    'Is this the end of all the endings? / My broken bones are mending',
    'I loved you in spite of deep fears that the world would divide us',
    'but I\'m the mess that you wanted',
    'But you stabbed me in the back while shaking my hand / And therein lies the issue / Friends don\'t try to trick you / Get you on the phone and mind-twist you / So I took an axe to a mended fence',
    'I brought a knife to a gunfight',
    'He built a fire just to keep me warm',
    'I want to wear his initial on a chain round my neck, not because he owns me, but cause he really knows me, which is more than they can say',
    'Holding my breath, slowly, I said \'You don\'t need to save me, but would you run away with me?\'',
    'Would\'ve been right there, front row even if nobody came to your show',
    'I\'m always waiting for you to be waiting below',
    'devils roll the dice, angels roll their eyes / What doesn\'t kill me makes me want you more',
    'I don\'t wanna keep secrets just to keep you',
    'I\'m drunk in the back of the car / And I cried like a baby coming home from the bar / Said, \'I\'m fine,\' but it wasn\'t true',
    'For whatever it\'s worth, I love you, ain\'t that the worst thing you ever heard?',
    'I\'ve got a hundred thrown-out speeches I almost said to you',
    'I am an architect, I\'m drawing up the plans',
    'I\'ll never let you go \'cause I know this is a fight that someday we\'re gonna win',
    'I\'m with you even if it makes me blue',
    'Without all the exes, fights, and flaws, we wouldn\'t be standing here so tall',
    'We were a fresh page on the desk, filling in the blanks as we go',
    'We were in the backseat drunk on something stronger than the drinks in the bar',
    'If the story is over, why am I still writing pages?',
    'I ask the traffic lights if it will be alright, they say I don\'t know.',
    'they say home is where the heart is, but that\'s not where mine lives',
    'I pinned your hands behind your back / Thought I had reason to attack, but no',
    'Fighting with a true love is boxing with no gloves / Chemistry \'til it blows up, \'til there’s no us',
    'And I can\'t talk to you when you\'re like this, staring out the window like I’m not your favorite town',
    'they say the road gets hard and you get lost',
    'remember how I said I\'d die for you?',
    'I come back stronger than a \'90s trend',
    'Wait for the signal, and I\'ll meet you after dark / Show me the places where the others gave you scars',
    'Bustling crowds or silent sleepers / You\'re not sure which is worse',
    'You told your family for a reason / You couldn\'t keep it in / Your sister splashed out on the bottle',
    'this dorm was once a madhouse\' I made a joke, \'Well, it\'s made for me\'',
    'One for the money, two for the show / I never was ready so I watch you go',
    'Sometimes you just don\'t know the answer \'til someone\'s on their knees and asks you',
    'I can\'t dare to dream about you anymore',
    'My mind turns your life into folklore / I can\'t dare to dream about you anymore',
    'I parked my car right between the Methodist and thе school that used to be ours',
    'I\'ll go back to L.A. and the so-called friends who\'ll write books about me if I ever make it and wonder about the only soul who can tell which smiles I\'m fakin',
    'What would you do if I break free and leave us in ruins, took this dagger in me and removed it, gain the weight of you then loose it?',
    'I made you my temple, my mural, my sky. Now I\'m begging for footnotes in the story of your life / Drawing hearts in the byline always taking up too much space or time',
    'Your nemesis will defeat themselves before you get the chance to swing',
    'My waves meet your shore ever and evermore',
    'I replay my footsteps on each stepping stone, trying to find the one where I went wrong',
    'So yeah, it\'s a fire, it\'s a goddamn blaze in the dark and you\'ve started it / So yeah, it\'s a war, it\'s the goddamn fight of my life and you started it',
    'did you ever hear about the girl who got frozen? / Time went on for everybody else, she won\'t know it / She\'s still twenty-three inside her fantasy',
    'Breaking down and coming undone / It\'s a rollercoaster kind of rush',
    'He can\'t see the smile I\'m faking and my heart\'s not breaking \'cause I\'m not feeling anything at all',
    'Well, I like the way your hair falls in your face / You got the keys to me / I love each freckle on your face',
    'With your face and the beautiful eyes / And the conversation with the little white lies / And the faded picture of a beautiful night',
    'Never be so kind / You forget to be clever / Never be so clever / You forget to be kind',
    'When you think Tim McGraw, I hope you think of me.'


];


// let btn=document.querySelector('.btn');
// btn.addEventListener('click', displayQuote);

function displayQuote(){
    //create an index of a random number
    //convert it into between 0 to length of quotes[]
    let index=Math.floor(Math.random()*quotes.length);

    //display the quote of that index
    let div=document.querySelector('#quote');
    let quote=`<p>"${quotes[index]}"</p>`;
    div.innerHTML=quote;
}
    displayQuote();

//$("checkbox").click(function(){
//  $("qcontainer").toggle("show");
//});


jQuery(document).ready(function(){
    jQuery('#hidequote').on('click', function(event) {
        jQuery('#content').toggle('show');
    });
});
